export const ADD_TO_CART = "ADD_TO_CART";
export const ADJUST_ITEM_QTY = "ADJUST_ITEM_QTY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";
export const ADD_ITEM_QTY = "ADD_ITEM_QTY";
export const SUBTRACT_ITEM_QTY = "SUBTRACT_ITEM_QTY";
